### ISSUE TITLE
MegaAge-Asian Testing Script

### ISSUE THREAD

**Issue by Charrin** [shamangary/SSR-Net#15]
Hi,  in your paper, you have tested SSR-Net model on MegaAge-Asian dataset and got result [CA(3): 0.549, CA(5):0.741]. 
I modified the script TYY_demo_mtcnn.py, use your "pre-trained/megaface_asian/ssrnet_3_3_3_64_1.0_1.0/ssrnet_3_3_3_64_1.0_1.0.h5" and read MegaAge-Asian images as input to test. 
But I can't get the approximate testing result, can you provide the testing script? Thank you!

**Comment by shamangary** [comment]
Please check the full code of MegaAge-Asian down here
https://github.com/b02901145/SSR-Net_megaage-asian

**Comment by Charrin** [comment]
Thank you!
