### ISSUE TITLE
change input size to 112X112

### ISSUE THREAD

**Issue by zhanglaplace** [shamangary/SSR-Net#19]
您好，请问下如果需要将输入图片修改为112X112，是否可以在第一个卷积前面加一个正常的3*3 ，stride为2的卷积就可以了。效果会比64X64的应该也会好吧。

**Comment by shamangary** [comment]
你好，理論上來說圖片越大自然細節越多，應該效果會變好，有幾種方法可以達到，你提的是其中一種，另外的可以是改變之後FC的大小，不過這需要計算到該層FC的neuron數量才能做到，個人選擇64x64只是因為這是通常最小的設定，128x128或更大的設定自然都是可以的 = )

**Comment by zhanglaplace** [comment]
@shamangary 好的，多谢回答，我找个时间做下实验，非常好的项目～👍

**Comment by blue-butterfly** [comment]
@shamangary
你好，您说的这个针对大于64*64的输入，解决方式 “另外的可以是改變之後FC的大小” 不太明白  可以解释下吗

**Comment by shamangary** [comment]
@blue-butterfly 你好，因為fully-connected基本上就是 y = W*x + b
你需要指定W矩陣的兩個維度（輸入和輸出），不然維度會對不上，
所以如果要改變input大小你就必須要算出使用FC layer時候的維度然後事前指定給FC才行這樣。

**Comment by blue-butterfly** [comment]
好的，明白了，非常感谢！！！！

**Comment by blue-butterfly** [comment]
@shamangary 感谢回复
