### ISSUE TITLE
Do you have plan to add gender classification?

### ISSUE THREAD

**Issue by scp-sjrim** [shamangary/SSR-Net#2]
Hello

it is amazing model.

but it doesn't give gender classification.

I know

https://github.com/shamangary/Keras-real-time-age-gender-estimation-demo

give gender but SSR-net is more good accuracy.

do you have plan to add gender classification?

**Comment by shamangary** [comment]
Hi. This project is specifically design to estimate age. Therefore, general classification is not directly applicable.

However, gender is a binary classification problem which can be turned into regression problem. (ex: male=1, female=0) It won't be too hard to add this feature.

I will add more extension in the future.

**Comment by shamangary** [comment]
I provide the gender regression training and webcam demo. Plz check that out!

**Comment by scp-sjrim** [comment]
@shamangary You're A amazing. Thanks!
