### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by zhly0** [shamangary/SSR-Net#21]
Hi，shamangary：
    how did you evaluate your cpu time？I use the following code to evaluate the inference time：
                start_CPU = timeit.default_timer()
                results = model.predict(faces)
                end_CPU = timeit.default_timer()
  in the TYY_demo_mtcnn.py code，but it takes about 20-30ms in cpu time，is it correct？

**Comment by shamangary** [comment]
Hello @zhly0. I don't have the exact number now since the time depends on your computer hardware, but it seems correct. Note that the slow part of the demo is the face detection part. So you need a fast face detection to achieve real-time.

**Comment by zhly0** [comment]
@shamangary . I test attribute model only，it seems to ten times slower than your model(in your paper,the cpu inference time is  2.69ms),I do not know if  the hardware makes the difference.
