### ISSUE TITLE
negative age

### ISSUE THREAD

**Issue by zhly0** [shamangary/SSR-Net#22]
Hi，shamangary：
        In the age prediction process，the age is negative，is there a way to avoid this？
Thanks。

**Comment by shamangary** [comment]
Hello @zhly0, in our funcion: https://github.com/shamangary/SSR-Net/blob/master/training_and_testing/SSRNET_model.py#L144
, the final prediction is 'age = (a+b+c)*V'

Considering the index is also controlled by the dynamic values 'index = (i+lambda_local*x[6][:,i])',
it is possible to cause negative values which is not supposed to happen. The solution could be:
(1) set lambda_local = 0 (2) change the initial index 'https://github.com/shamangary/SSR-Net/blob/master/training_and_testing/SSRNET_model.py#L301': from 0 to 1 and do the same in the three for loop.

**Comment by zhly0** [comment]
Thanks，I will try！
