### ISSUE TITLE
预测值没有年龄15岁以下的

### ISSUE THREAD

**Issue by wangjing60755** [shamangary/SSR-Net#24]
拿模型predict的时候，发现小孩儿and 婴儿，全部预测15+岁。我看那个megaage-asian数据集是0-70,所以为什么我预测没有小孩那一段的，是模型本身的局限还是我哪里没搞对？？

**Comment by shamangary** [comment]
嗨 @wangjing60755，我們在測試的時候也有發現類似的問題，不過因為應用層面我們沒有專注在小孩當時我們就忽略了，不過你是對的，這件事情不該發生，我們會在以後的版本改善，目前比較沒有時間就是
