### ISSUE TITLE
another question

### ISSUE THREAD

**Issue by alexliyang** [shamangary/SSR-Net#26]
HI, @shamangary can I use this net to train age and gender at the same time? and if gender has 3 classes ,ie (0: other, 1: female, 2: male) , in merge_age function V should be set V=1 or V=3?

**Comment by shamangary** [comment]
Training multiple outputs under SSR-Net structure is more related to my next work FSA-Net
https://github.com/shamangary/FSA-Net
But how to merge two completely different domain information is the future topic I have in mind. There is no solid solution in this project for that now.

**Comment by alexliyang** [comment]
@shamangary 
thanks , I'll study FSA-NET.

and can I use like this:
            age = (a+b+c)*V
            gender = (a+b+c)
            return age,gender

 than , count age_mae and gender_mae loss , use the same pre net ,then get two result?

**Comment by shamangary** [comment]
It is possible, but I never try that so I cannot confirm the performance.

**Comment by alexliyang** [comment]
OK, I try it :)
