### ISSUE TITLE
请问您在预处理数据的时候对图像进行人脸识别并裁剪了吗？

### ISSUE THREAD

**Issue by Leon-Zijie-Li** [shamangary/SSR-Net#30]
您好，在预处理数据（create_db.py）时，我注意到你对原本数据集的图像进行了人脸识别，但好像并未对人脸部分进行裁剪。（若是看错，还请谅解）
当我利用MegaAsian的数据集进行训练时，我发现该数据集人脸外的背景并不小，担心“噪声”较大，这样训练的结果是否会对结果造成影响呢？（我裁剪后，对于小孩的判断有一定提升）
不知道您的看法如何？谢谢。

**Comment by Leon-Zijie-Li** [comment]
另外，在TYY_Megaage_asian_create_db.py里，您有写一句“#only add to the list when faces is detected”，但我看代码里并无使用mtcnn的方式来检测人脸（而Morph的数据中，您则检测处理了）。

**Comment by shamangary** [comment]
@Leon-Zijie-Li 你好，在訓練過程中我預設是在偵測完人臉後，放大一定的比例，例如說1->1.4倍大小，在Megaage-Asian的部分我印象中他們已經有做過人臉對齊和偵測，所以印象中當初就沒有做任何偵測了，畢竟mtcnn有時候還是會沒有偵測到，理想上有更好的

**Comment by Leon-Zijie-Li** [comment]
的确是已经做过一定的检测和对齐，了解您的意思，谢谢您的及时回复啦。
