### ISSUE TITLE
how to implement model.predict() function in TYY_demo_mtcnn.py using c++ 

### ISSUE THREAD

**Issue by liangheng** [shamangary/SSR-Net#32]
I need to engineer ssrnet. How do I plan my final age by getting 9 output nodes（ pred_age_stage1、 pred_age_stage2、 pred_age_stage3、delta_s1、delta_s2、delta_s3、local_delta_stage1、local_delta_stage2、local_delta_stage3）?

Who can help me? Thank you

**Comment by shamangary** [comment]
https://github.com/shamangary/SSR-Net/blob/master/training_and_testing/SSRNET_model.py#L295
Just follow this function and write a C++ version
