### ISSUE TITLE
using Megaage-Asian train mae is 3.8,is this normal？

### ISSUE THREAD

**Issue by zys1994** [shamangary/SSR-Net#33]
i train ssrnet with  Megaage-Asian and get the  mae is 3.8,is this normal？ what's your result about Megaage-Asian.  Thanks

**Comment by shamangary** [comment]
Hello. We didn't test MAE on Megaage-Asian. It was CA on the other repository.

**Comment by happyprotean** [comment]
Hi @zys1994 I trained with Megaage-Asian and get mae is 3.91 which is lower than you. Have you ever change the original code somewhere? Thanks

**Comment by shamangary** [comment]
We didn't test MAE on Megaage-Asian. It was CA on the other repository.
BTW, the batchsize and the version of the tensorflow and keras you use might affect the results too.

**Comment by happyprotean** [comment]
Thanks for your reply, @shamangary . Maybe you are right because I also get the CA result on MegaAge-Asian, which CA3=0.536, CA5=0.731. It is sight lower than your result: CA3=0.549, CA5=0.741. I didn't change the code except some modification caused by keras version.
