### ISSUE TITLE
转caffe模型得到结果不太一直，想向您确认一下预处理形式

### ISSUE THREAD

**Issue by zys1994** [shamangary/SSR-Net#34]
模型转换后得到的[pred_a_s1,pred_a_s2,pred_a_s3,delta_s1,delta_s2,delta_s3, local_s1, local_s2, local_s3]不太一致。 根据你的demo, 我把格式设成了一致的，mean设为0，scale设为1，图像类型为BGR，未做对齐。想向您确认一下预处理是否不当？

**Comment by shamangary** [comment]
Hello. Alignment is actually a necessary part for the age estimation, the demo didn't include that for simplicity. 
For the input, I use unnormalized images (0~255), but you can always normalize the input and retrain the network.

**Comment by zys1994** [comment]
i have noticed your word. i want to make sure the scale is[0-255],mean[0，0，0]，type:bgr?

**Comment by shamangary** [comment]
RGB I think. But I also remember that won't make big difference.

**Comment by zys1994** [comment]
some mistakes may happen in convertion, thanks for your advices
