### ISSUE TITLE
Why stage1 (layer4) has no pooling layer?

### ISSUE THREAD

**Issue by Pirate-Pianist** [shamangary/SSR-Net#35]
Excuse me. I read your code and I didn't see any pooling layer(AvgPooling or MaxPooling) in Stage1(code: layer4). But it does actually exist in Stage3(code: layer1) and Stage2(code: layer2).

Why is this difference? Thank you.

**Comment by Pirate-Pianist** [comment]
Is this because the deeper layer has more detail information that may be blured by pooling layer?

**Comment by shamangary** [comment]
Hello. I was trying to make the structure more consistent and make three stages have similar output size. In our new work FSA-Net, I further make three stages have the exact same size (8x8) so they can share the same mapping function. As for the performance, I have not tested different choices. Feel free to try more combinations.

**Comment by Pirate-Pianist** [comment]
Thanks a lot~
