### ISSUE TITLE
What are `lambda_local` and `lambda_d` before $\eta$ and $\Delta_k$ respectively?

### ISSUE THREAD

**Issue by Pirate-Pianist** [shamangary/SSR-Net#36]
Hello. In paper **3.3 Dymamic Range** part, 
formula (4)
    $$\bar s_k = s_k (1 + \Delta_k)  \tag{4}$$
formula (6)
    $$\bar i = i + \eta_i^{(k)}  \tag{6}$$

but there is sort of different in the code, the $\Delta_k$ and $\eta$ are multiplied by `lambda_local` and `lambda_d` respectively which (`lambda_local` and `lambda_d`) are assigned [0, 0.25, 0.5, 0.75, 1] in the *SSRNET_train.py*. 

Why are they(`lambda_local` and `lambda_d`)  exist?
Thank you.

**Comment by shamangary** [comment]
Hello. lambda_local and lambda_d are basically hyperparameters for tuning dynamic indexing and dynamic scaling.

**Comment by Pirate-Pianist** [comment]
Thank you.
