### ISSUE TITLE
.h5 model to .pb model but output node is strange!

### ISSUE THREAD

**Issue by A1exy** [shamangary/SSR-Net#37]
I transfer h5 model to .pb model but output node is strange, the output node is pred_a/mul_33, I can't find this node in the tensorflow graph,  do you know the reason,  thanks!

![image](https://user-images.githubusercontent.com/7035538/64221377-48826c00-ceff-11e9-8b06-f9c87a3b9ebd.png)

![image](https://user-images.githubusercontent.com/7035538/64221410-618b1d00-ceff-11e9-8c5b-c4026e338c6a.png)

![image](https://user-images.githubusercontent.com/7035538/64222008-5638f100-cf01-11e9-9a74-73fd7737ac7b.png)

find pred_a/mul_33 node, but I don't know what the node means.

**Comment by shamangary** [comment]
https://github.com/shamangary/SSR-Net/blob/master/training_and_testing/SSRNET_model.py#L170
Hello. Please check this line. pred_a is basically the final ssr-module for putting everything together into a single age prediction. 

I am not familiar with your tool, but the graph representation can be found in https://github.com/shamangary/SSR-Net/blob/master/pre-trained/morph2/ssrnet_3_3_3_64_1.0_1.0/ssrnet_3_3_3_64_1.0_1.0.png

As for our extension FSA-Net has a more structure organization similiar to SSR-Net as well.
Please check
https://github.com/shamangary/FSA-Net/blob/master/pre-trained/300W_LP_models/fsanet_capsule_3_16_2_21_5/ssrnet_R2_capsule_3_16_2_21_5.png
and the png files inside the same folder.

**Comment by A1exy** [comment]
Thanks for your reply. The structure of the transferred pb model looks correct, but the output node pred_a/mul_33 is very strange,  Keras inference is right, but tensorflow is wrong.

![image](https://user-images.githubusercontent.com/7035538/64222350-584f7f80-cf02-11e9-9b3f-6d69e47e7ba9.png)

**Comment by shamangary** [comment]
My guess is that the Lambda layer in Keras is not directly transferable to Tensorflow. So maybe the function of the SSR-Module is not really working now. Maybe an adapted version of such module is needed for tensorflow somehow.

**Comment by A1exy** [comment]
Thanks.
