### ISSUE TITLE
a Pytorch reimplementation of SSRNet.

### ISSUE THREAD

**Issue by oukohou** [shamangary/SSR-Net#42]
@shamangary 你好，求大佬在`readme`的`third party implementation`里多加个链接哈哈～～：

Pytorch: [https://github.com/oukohou/SSR_Net_Pytorch](https://github.com/oukohou/SSR_Net_Pytorch)

让我也能蹭一波大佬的热度～～～谢谢～～

**Comment by shamangary** [comment]
Sure. Thanks for your implementation.
