### ISSUE TITLE
How to explain “netType1”“netType2” and “lambda_local”“lambda_local”?

### ISSUE THREAD

**Issue by linlinle** [shamangary/SSR-Net#6]
hello! @shamangary 

I want to understand what  “netType1”“netType2” and “lambda_local”“lambda_local” stand for?

Thank you very much for your answer!

**Comment by shamangary** [comment]
Hello. netType1 and netType2 are just the indices for two different for loop in the shell file.
I want to use different hyperparameters to evaluate the results of our method.
```
lambda_local = 0.25*(netType1%5)
lambda_d = 0.25*(netType2%5)
```
For example, if netType1 equals to 4, then lambda_local is 1.0.

lambda_local is the dynamic factor of the index.
lambda_d is the dynamic factor of the neuron number in the denominator.

**Comment by linlinle** [comment]
ok, 
Can I think of “lambda_local” “lambda_d” as the **attenuation coefficient** for offset vector local_{k} and delta_{k}?
